[root]
# Root path
# Default is fancyndex folder's parent
path = "/home/spoken/"

[walk_opt]
# Handle hidden files (.dotfiles)?
# Default false
hidden = true

# Handle symbolic link ?
# Default false
symlink = true
