[root]
# Root path
# Default is fancyndex folder's parent
path = ""

[walk_opt]
# Handle hidden files (.dotfiles)?
# Default false
hidden = true

# Handle symbolic link ?
# Default false
symlink = true

[entries_opt]
# Datetime format :
dtime_format = "%Y-%m-%d %T"

# Wanted unit size
# 
# one byte equals to :
# true -> 1024 bits
# false -> 1000 bits
# 
# Default true
unit_size = true

float_precision = 2
