[root]
# Root path
# Default is fancyndex folder's parent
path = "/home/spoken/Git"

[walk_opt]
# Handle hidden files (.dotfiles)?
# Default false
hidden = false

# Handle symbolic link ?
# Default false
symlink = true
