// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_directory
#define IOD_SYMBOL_directory
    iod_define_symbol(directory)
#endif

#ifndef IOD_SYMBOL_path
#define IOD_SYMBOL_path
    iod_define_symbol(path)
#endif

#ifndef IOD_SYMBOL_root
#define IOD_SYMBOL_root
    iod_define_symbol(root)
#endif

#ifndef IOD_SYMBOL_size
#define IOD_SYMBOL_size
    iod_define_symbol(size)
#endif

