// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_ascending_name
#define IOD_SYMBOL_ascending_name
    iod_define_symbol(ascending_name)
#endif

#ifndef IOD_SYMBOL_by_date
#define IOD_SYMBOL_by_date
    iod_define_symbol(by_date)
#endif

#ifndef IOD_SYMBOL_by_name
#define IOD_SYMBOL_by_name
    iod_define_symbol(by_name)
#endif

#ifndef IOD_SYMBOL_by_size
#define IOD_SYMBOL_by_size
    iod_define_symbol(by_size)
#endif

#ifndef IOD_SYMBOL_decreasing_name
#define IOD_SYMBOL_decreasing_name
    iod_define_symbol(decreasing_name)
#endif

#ifndef IOD_SYMBOL_dir
#define IOD_SYMBOL_dir
    iod_define_symbol(dir)
#endif

#ifndef IOD_SYMBOL_mode
#define IOD_SYMBOL_mode
    iod_define_symbol(mode)
#endif

#ifndef IOD_SYMBOL_path
#define IOD_SYMBOL_path
    iod_define_symbol(path)
#endif

#ifndef IOD_SYMBOL_size
#define IOD_SYMBOL_size
    iod_define_symbol(size)
#endif

#ifndef IOD_SYMBOL_unit
#define IOD_SYMBOL_unit
    iod_define_symbol(unit)
#endif

