// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_active_path
#define IOD_SYMBOL_active_path
    iod_define_symbol(active_path)
#endif

#ifndef IOD_SYMBOL_archive
#define IOD_SYMBOL_archive
    iod_define_symbol(archive)
#endif

#ifndef IOD_SYMBOL_dir
#define IOD_SYMBOL_dir
    iod_define_symbol(dir)
#endif

#ifndef IOD_SYMBOL_list
#define IOD_SYMBOL_list
    iod_define_symbol(list)
#endif

#ifndef IOD_SYMBOL_mode
#define IOD_SYMBOL_mode
    iod_define_symbol(mode)
#endif

#ifndef IOD_SYMBOL_ok
#define IOD_SYMBOL_ok
    iod_define_symbol(ok)
#endif

#ifndef IOD_SYMBOL_path
#define IOD_SYMBOL_path
    iod_define_symbol(path)
#endif

#ifndef IOD_SYMBOL_sort
#define IOD_SYMBOL_sort
    iod_define_symbol(sort)
#endif

